### ISSUE TITLE
Can you explain what you achieved?

### ISSUE THREAD

**Issue by ageorgios** [liaan/paradox_esp8266#1]
What is the function of this implementation?

**Comment by liaan** [comment]
Hi, 

Basically to connect to ESP8266 to the paradox alarm system bus and send the status of the alarm to a MQTT server.

Currently ESP8266 is read only, the arduino version can set alarm etc. all still work in progress though

**Comment by jean-jcrx** [comment]
How long before you will be able to set alarm via ESP8266?
